name = "involvex-db"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "involvex-production"
database_id = "" # Will be set after creating database with `bun run create`
