name: check_releases
description: Appwrite function to check for new releases on subscribed repositories and packages
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dart_appwrite: ^13.0.0
  dio: ^5.4.0
