title: Involvex User Guide
description: Mobile app for tracking trending GitHub repos and npm packages
theme: jekyll-theme-hacker
baseurl: "/trending-hub-rn"  # Update this to match your repository name if it's different
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
