title: Involvex User Guide
description: Neural-link dashboard for trending open-source protocols.
remote_theme: pages-themes/hacker@v0.2.0
baseurl: "/involvex-android-app"
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
