title: Involvex User Guide
description: Mobile app for tracking trending GitHub repos and npm packages
theme: jekyll-theme-hacker
baseurl: "/involvex-android-app"
# remote_theme: pages-themes/hacker@v0.2.0
# plugins:
#   - jekyll-remote-theme
