title: Involvex User Guide
description: Neural-link dashboard for trending open-source protocols.
theme: jekyll-theme-hacker
baseurl: "/involvex-android-app"
# Ensure the theme is loaded from GitHub
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true